name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:  
  e2eTests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Install Python dependencies
      run: |
        cd playwrightPy
        poetry install
        poetry run playwright install --with-deps
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*        
    - name: Install Server dependencies
      run: |
        cd testApp
        npm ci --force
    - name: Install Node Playwright dependencies
      run: |        
        cd playwrightSpecs
        npm ci
        npx playwright install --with-deps
    - name: Start the test server
      run: |
        cd testApp
        npm run start &
        npx wait-on http://localhost:4200/ --timeout 60000  # Wait up to 60 seconds (60000 milliseconds) for the server to be up
    - name: Run Playwright node Tests
      run: |        
        cd playwrightSpecs
        npx playwright test     
    - name: Run Playwright python Tests
      run: |        
        cd playwrightPy
        pytest
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
